services:
  mainframe-db2-cobol:
    build: ./db2-cobol               
    container_name: mydb2_moderno
    privileged: true                    
    ports:
      - "50000:50000"                
      - "9000:9000"                   
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=Password1
      - DBNAME=TESTDB
      - LD_LIBRARY_PATH=/opt/ibm/db2/V11.5/lib64:$$LD_LIBRARY_PATH
    volumes:
      - .:/project                     
      - db2_sistema:/database           
      - db2_alta_disponibilidad:/hadr   
    networks:
      - red-banco

    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "50000"]
      interval: 10s
      timeout: 5s
      retries: 20
      
  #-----------------------------------

  api-springboot:
    build: ./api-springboot       
    container_name: api_banco_moderno
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:db2://mydb2_moderno:50000/TESTDB
      - SPRING_DATASOURCE_USERNAME=db2inst1
      - SPRING_DATASOURCE_PASSWORD=Password1
    networks:
      - red-banco
    depends_on:
      mainframe-db2-cobol: 
        condition: service_healthy   

networks:
  red-banco:
    driver: bridge                     

volumes:
  db2_sistema:                                  
  db2_alta_disponibilidad: