DROP TABLE CLIENTE;
DROP TABLE SALDO;
DROP TABLE CUENTA;
DROP TABLE MOVIMIENTO;


CREATE TABLE CLIENTE (
ID_CLIENTE INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
NOMBRE VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(20) NOT NULL,
DNI VARCHAR(9) NOT NULL UNIQUE,
PRIMARY KEY (ID_CLIENTE));

-----------------------------------------------------

CREATE TABLE SALDO (
ID_SALDO INT NOT NULL GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
EFECTIVO_DISPONIBLE NUMERIC(12,2) DEFAULT 0.00,
EFECTIVO_EMBARGADO NUMERIC(12,2) DEFAULT 0.00,
PRIMARY KEY (ID_SALDO));

-----------------------------------------------------

CREATE TABLE CUENTA (
ID_CUENTA INT NOT NULL GENERATED AS IDENTITY (START WITH 1 INCREMENT BY 1),
ID_CLIENTE INT NOT NULL,
ID_SALDO INT NOT NULL,
IBAN CHAR(24) NOT NULL,
PRIMARY KEY (ID_CUENTA),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE,
FOREIGN KEY (ID_SALDO) REFERENCES SALDO);

-----------------------------------------------------------

CREATE TABLE MOVIMIENTO (
    ID_MOVIMIENTO INT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    ID_CLIENTE INT NOT NULL,
    ID_CUENTA INT NOT NULL,
    FECHA TIMESTAMP DEFAULT CURRENT TIMESTAMP,
    TIPO VARCHAR(1) NOT NULL,
    ID_CUENTA_DESTINO INT,
    DINERO_TRANSFERIDO NUMERIC(12,2),
    DINERO_INGRESADO NUMERIC(12,2),
    NOMBRE_SERVICIO VARCHAR(40),
    PAGO NUMERIC(12,2),
    DINERO_EXTRAIDO NUMERIC(12,2),
    PRIMARY KEY (ID_MOVIMIENTO),
    FOREIGN KEY (ID_CUENTA) REFERENCES CUENTA(ID_CUENTA) ON DELETE RESTRICT,
    
    CONSTRAINT CK_MOV_TOTALIDAD CHECK (TIPO IN ('I','T','P','E')),
    
    CONSTRAINT CK_MOV_EXCLUSIVIDAD CHECK (
        (TIPO = 'I' AND DINERO_INGRESADO IS NOT NULL AND ID_CUENTA_DESTINO IS NULL AND DINERO_TRANSFERIDO IS NULL AND NOMBRE_SERVICIO IS NULL AND PAGO IS NULL AND DINERO_EXTRAIDO IS NULL) OR
        (TIPO = 'T' AND ID_CUENTA_DESTINO IS NOT NULL AND DINERO_TRANSFERIDO IS NOT NULL AND DINERO_INGRESADO IS NULL AND NOMBRE_SERVICIO IS NULL AND PAGO IS NULL AND DINERO_EXTRAIDO IS NULL) OR
        (TIPO = 'P' AND PAGO IS NOT NULL AND NOMBRE_SERVICIO IS NOT NULL AND ID_CUENTA_DESTINO IS NULL AND DINERO_TRANSFERIDO IS NULL AND DINERO_INGRESADO IS NULL AND DINERO_EXTRAIDO IS NULL) OR
        (TIPO = 'E' AND DINERO_EXTRAIDO IS NOT NULL AND ID_CUENTA_DESTINO IS NULL AND DINERO_TRANSFERIDO IS NULL AND DINERO_INGRESADO IS NULL AND PAGO IS NULL AND NOMBRE_SERVICIO IS NULL)
    )
);

