services:
  mainframe-db2-cobol:
    build: ./db2-cobol               
    container_name: mydb2_moderno
    privileged: true                    
    ports:
      - "50000:50000"                
      - "9000:9000"                   
    environment:
      - LICENSE=accept
      - DB2INST1_PASSWORD=Password1
      - DBNAME=TESTDB
    volumes:
      - .:/project                     
      - db2_sistema:/database           
      - db2_alta_disponibilidad:/hadr   
    networks:
      - red-banco

networks:
  red-banco:
    driver: bridge                     

volumes:
  db2_sistema:                          
  db2_alta_disponibilidad: